config/routes.rb
Ticketee::Application.routes.draw do
  devise_for :users

  resources :projects do
    resources :tickets
  end

  root :to => "projects#index"

end

app/models/project.rb
#encoding: utf-8

class Project < ActiveRecord::Base

  has_many :tickets, :dependent => :nullify

  validates_presence_of :name, :message => "名称 不能为空"
end

app/models/ticket.rb
#encoding: utf-8

class Ticket < ActiveRecord::Base

  belongs_to :user
  belongs_to :project

  validates :title, :presence => { :message => "标题 必须填写" }
  validates :description, :presence => { :message => "描述 必须填写" },
            :length => { :minimum => 3 }

  # validates_presence_of :title, :message => "标题 必须填写"
  # validates_presence_of :description, :message => "描述 必须填写"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
#encoding: utf-8

class ProjectsController < ApplicationController

  before_filter :find_project, :only => [:show,
                                         :edit,
                                         :update,
                                         :destroy]

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      flash[:notice] = "工程创建成功！"
      redirect_to @project
    else
      flash[:alert] = "工程创建失败。"
      render :action => :new
    end
  end

  def show
    # @project = Project.find(params[:id])
  end

  def edit
    # @project = Project.find(params[:id])
  end

  def update
    # @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      flash[:notice] = "工程已成功修改。"
      redirect_to @project
    else
      flash[:notice] = "工程修改失败。"
      render :action => :edit
    end
  end

  def destroy
    # @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "工程已成功删除。"
    redirect_to projects_path
  end

  private
    def find_project
      begin
        @project = Project.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        flash[:alert] = "工程没有找到。"
        redirect_to projects_path
      end
    end
end

app/controllers/tickets_controller.rb
#encoding: utf-8

class TicketsController < ApplicationController

  before_filter :authenticate_user!, :except => [ :index, :show ]
  before_filter :find_project
  before_filter :find_ticket, :only => [:show, :edit, :update, :destroy]

  def new
    @ticket = @project.tickets.build
  end

  def create
    @ticket = @project.tickets.build(params[:ticket].merge!(:user => current_user))
    if @ticket.save
      flash[:notice] = "票样已成功创建。"
      redirect_to [@project, @ticket]
      # redirect_to project_ticket_path(@project, @ticket)
    else
      flash[:alert] = "票样创建失败。"
      render :action => :new
    end
  end

  def show

  end

  def edit

  end

  def update
    if @ticket.update_attributes(params[:ticket])
      flash[:notice] = "票样已更新成功。"
      redirect_to [@project, @ticket]
    else
      flash[:alert] = "票样更新失败。"
      render :action => :edit
    end
  end

  def destroy
    @ticket.destroy
    flash[:notice] = "票样已成功删除。"
    redirect_to @project
  end

  private
    def find_project
      @project = Project.find(params[:project_id])
    end

    def find_ticket
      @ticket = @project.tickets.find(params[:id])
    end
end

app/helpers/application_helper.rb
#encoding: utf-8

module ApplicationHelper
  # 数组方式定义title，用" - "来连接
  def title(*parts)
=begin
    unless parts.empty?
      content_for :tilte do
        (parts << "Ticketee").join(" - ") unless parts.empty?
      end
    end
=end
    @title = (parts << "Ticketee").join(" - ") unless parts.empty?
    @title || "Ticketee"
  end

  def error_messages_for(object_name, options = {})
    options = options.symbolize_keys
    object = instance_variable_get("@#{object_name}")
    unless object.errors.empty?
      error_lis = []
      object.errors.each{ |key, msg| error_lis << content_tag("li", msg) }
      content_tag("div", content_tag(options[:header_tag] || "h2", "发生#{object.errors.count}个错误" ) +
          content_tag("ul", raw(error_lis)), "id" => options[:id] || "errorExplanation", "class" => options[:class] || "errorExplanation" )
    end
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
  <%#= link_to "注册", new_user_registration_path  %>
  <% if user_signed_in? %>
    您：<%= current_user.email %> 已登陆。
  <% else %>
    <%= link_to "注册", new_user_registration_path %>
  <% end %>
</nav>

<%= link_to '登陆', new_user_session_path  %>
<% flash.each do |key, value| %>
 <div class="flash" id="<%= key %>">
   <%= value %>
 </div>
<% end %>

<h1><%= link_to 'Ticketee', root_path  %></h1>
<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%#= error_messages_for f.object_name %>
<%= f.error_messages%>
<p>
  <%= f.label :name, "名称：" %>
  <%= f.text_field :name%>
</p>

app/views/projects/edit.html.erb
<h2>修改工程</h2>
<%= form_for @project do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit '修改工程' %>
<% end %>

app/views/projects/index.html.erb
<h2>工程</h2>
<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

<%= link_to '新建工程', new_project_path %>

app/views/projects/new.html.erb
<h2>新建工程</h2>
<%= form_for @project do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit '创建工程' %>
<% end %>

app/views/projects/show.html.erb
<% title(@project.name, controller_name.capitalize)%>
<h2><%= @project.name %></h2>
<ul id="tickets">
  <% @project.tickets.each do |ticket| %>
    <li>
      #<%= ticket.id %> - <%= link_to ticket.title, [@project, ticket] %>
    </li>
  <% end %>
</ul>
<%= link_to "修改工程", edit_project_path(@project) %>
<%= link_to "删除工程", @project, :method => :delete,
    :confirm => "您确定删除?" %>
<%= link_to "新建票样", new_project_ticket_path(@project) %>

app/views/tickets/_form.html.erb
<%= f.error_messages %>
<p>
  <%= f.label :title, "标题" %>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :description, "描述" %>
  <%= f.text_field :description %>
</p>

app/views/tickets/edit.html.erb
<h2>修改<%= @project.name %>的票样</h2>
<%= form_for [@project, @ticket] do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit '更新票样' %>
<% end %>

app/views/tickets/new.html.erb
<h2>新建票样</h2>
<%= form_for [@project, @ticket] do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit '创建票样' %>
<% end %>

app/views/tickets/show.html.erb
<br><small>由<%=@ticket.user.email %>创建。
<div id="ticket">
  <h2><%= @ticket.title %></h2>
  <%= simple_format(@ticket.description) %>
</div>
<%= link_to '修改票样', [:edit, @project, @ticket] %>
<%= link_to '删除票样', [@project, @ticket], :method => :delete,
    :confirm => "您确定删除票样吗?" %>